# The same as the train.yaml but you could customize the parameters for testing.
data:
  class_path: data_loader.SPencn_NSdns_RIRreal.CleanMelDataModule
  init_args:
    speech_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/Hebrew_Dataset/he/clean_hebrew_16k/

    # The HF Noise Path (from your code)
    noise_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/datasets/noise/

    # The OpenSLR RIR Path (from your code)
    rir_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/RIRS_NOISES/real_rirs_isotropic_noises/
    datasets: ['SimTrain', 'SimVal', 'SimTest', ['SimVal']]
    audio_time_len: [4.0, 4.0, null]
    snr: [-5, 20]
    batch_size: [2, 1]
    dataset_len: [5000, 200, 200]

#model_checkpoint: # remove this if it cause any errors
#  save_top_k: -1 # save every checkpoint for testing the performance on utterance/session0 and pick the best checkpoint for evaulating other sessions