
data:
  class_path: data_loader.SPencn_NSdns_RIRreal_rts.CleanMelDataModule
  init_args:
    speech_dir: ./datasets/he/clean_hebrew_16k/
    noise_dir: ./datasets/noise/
    rir_dir: ./datasets/RIRS_NOISES/real_rirs_isotropic_noises/
    datasets: ['SimTrain', 'SimVal', 'SimTest', ['SimVal']]
    audio_time_len: [4.0, 4.0, 4.0]
    snr: [-5, 20]
    batch_size: [2, 20]     # Adjusted to match your command line args
    dataset_len: [4392, 549, 550]

model_checkpoint: # remove this if it cause any errors
  save_top_k: -1 # save every checkpoint for testing the performance on utterance/session0 and pick the best checkpoint for evaulating other sessions