data:
  class_path: data_loader.SPencn_NSdns_RIRreal.CleanMelDataModule
  init_args:
    # Pointing to your converted 16kHz Hebrew WAVs
    speech_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/Hebrew_Dataset/he/clean_hebrew_16k/

    # The HF Noise Path (from your code)
    noise_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/datasets/noise/

    # The OpenSLR RIR Path (from your code)
    rir_dir: /content/drive/MyDrive/Audio_Course_Final_Project/CleanMel/RIRS_NOISES/real_rirs_isotropic_noises/

    datasets: ['SimTrain', 'SimVal', 'SimTest', ['SimVal']]
    audio_time_len: [4.0, 4.0, null]
    snr: [-5, 20]
    batch_size: [2, 1]

    # CRITICAL CHANGE: Adjusted to match your actual file count (~5500 files)
    # [Train, Val, Test]
    dataset_len: [5000, 200, 200]

#model_checkpoint:
#  save_top_k: -1
#  monitor: "val_loss"
#  mode: "min"
#  dirpath: "checkpoints/hebrew_finetune"
#  filename: "cleanmel-hebrew-{epoch:02d}-{val_loss:.2f}"