data:
  # Use the robust dataloader we decided on
  class_path: data_loader.SPencn_NSdns_RIRreal_rts.CleanMelDataModule
  init_args:
    # Relative paths to your local datasets
    speech_dir: ./datasets/he/clean_hebrew_16k/
    noise_dir: ./datasets/noise/
    rir_dir: ./datasets/RIRS_NOISES/real_rirs_isotropic_noises/

    # Standard split names
    datasets: ['SimTrain', 'SimVal', 'SimTest', ['SimVal']]

    # Audio length: 4s for training, full length (null) for validation
    audio_time_len: [4.0, 4.0, 4.0]

    # SNR range for mixing noise
    snr: [-5, 20]

    # Batch Size: [Train, Val]
    # We use 8 for training (faster) and 1 for val (safest for variable lengths)
    batch_size: [4, 1]

    # Dataset Lengths: [Train, Val, Test]
    dataset_len: [4392, 549, 550]
    #dataset_len: [40, 10, 10]

# Optional: Uncomment to customize checkpoint saving
# model_checkpoint:
#   save_top_k: 3
#   monitor: "val_loss"
#   mode: "min"
#   dirpath: "checkpoints/hebrew_finetune"
#   filename: "cleanmel-hebrew-{epoch:02d}-{val_loss:.2f}"